// AUTO-GENERATED by src-tauri/src/engine/action_def.rs
// Do not edit manually. Run `cargo build` to regenerate.

export type ActionCategory =
  | 'navigation'
  | 'interaction'
  | 'data_read'
  | 'data_write'
  | 'file_operation'
  | 'system'
  | 'clipboard'
  | 'reporting'

export type ParamType = 'text' | 'number' | 'select' | 'checkbox' | 'textarea' | 'variable_ref' | 'file_path'

export interface ParamDef {
  key: string
  label: string
  param_type: ParamType
  required?: boolean
  default_value?: unknown
  placeholder?: string
  options?: { label: string; value: string }[]
  hint?: string
}

export interface ActionDef {
  action_type: string
  label: string
  category: ActionCategory
  description: string
  params: ParamDef[]
  output_hint?: string
}

export const CONTAINER_ACTIONS: Record<string, ActionDef[]> = {
  browser: [
    {
      action_type: 'navigate',
      label: 'Navigate',
      category: 'Navigation',
      description: 'Navigate to a URL',
      params: [
        { key: 'url', label: 'URL', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ url, title }',
    },
    {
      action_type: 'click',
      label: 'Click',
      category: 'Interaction',
      description: 'Click an element by CSS selector',
      params: [
        { key: 'selector', label: 'CSS Selector', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'input',
      label: 'Type Text',
      category: 'Interaction',
      description: 'Type text into an input field',
      params: [
        { key: 'selector', label: 'CSS Selector', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'text', label: 'Text', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'scroll',
      label: 'Scroll',
      category: 'Interaction',
      description: 'Scroll the page by pixels',
      params: [
        { key: 'amount', label: 'Scroll Amount (px)', param_type: 'Number', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'extract',
      label: 'Extract Content',
      category: 'DataRead',
      description: 'Extract text or HTML from elements',
      params: [
        { key: 'selector', label: 'CSS Selector', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'mode', label: 'Extract Mode', param_type: 'Select', required: false, default_value: undefined, placeholder: undefined, options: [{ label: 'Text', value: 'text' }, { label: 'HTML', value: 'html' }, { label: 'Attribute', value: 'attribute' }], hint: undefined },
        { key: 'attribute', label: 'Attribute Name', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ text, html, count }',
    },
    {
      action_type: 'screenshot',
      label: 'Screenshot',
      category: 'DataRead',
      description: 'Take a screenshot of the page',
      params: [
        { key: 'mode', label: 'Mode', param_type: 'Select', required: false, default_value: undefined, placeholder: undefined, options: [{ label: 'Full Page', value: 'full' }, { label: 'Viewport', value: 'viewport' }, { label: 'Element', value: 'element' }], hint: undefined },
        { key: 'selector', label: 'Element Selector', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ path, base64 }',
    },
    {
      action_type: 'wait',
      label: 'Wait',
      category: 'System',
      description: 'Wait for an element or timeout',
      params: [
        { key: 'selector', label: 'Wait for selector', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'timeout_ms', label: 'Timeout (ms)', param_type: 'Number', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'hover',
      label: 'Hover',
      category: 'Interaction',
      description: 'Hover over an element',
      params: [
        { key: 'selector', label: 'CSS Selector', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'press_key',
      label: 'Press Key',
      category: 'Interaction',
      description: 'Press a keyboard key or combination',
      params: [
        { key: 'key', label: 'Key (e.g. Enter, Ctrl+C)', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
  ],
  excel: [
    {
      action_type: 'read',
      label: 'Read Data',
      category: 'DataRead',
      description: 'Read cells from a sheet',
      params: [
      ],
      output_hint: '{ sheet, data, rows, cols }',
    },
    {
      action_type: 'write',
      label: 'Write Data',
      category: 'DataWrite',
      description: 'Write structured data to the sheet',
      params: [
        { key: 'value', label: 'Data (array of arrays)', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'create',
      label: 'Create Workbook',
      category: 'DataWrite',
      description: 'Create a new Excel file with headers',
      params: [
        { key: 'headers', label: 'Column Headers (comma-separated)', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'append',
      label: 'Append Row',
      category: 'DataWrite',
      description: 'Append a row to the existing sheet',
      params: [
        { key: 'value', label: 'Row data (array)', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'sort',
      label: 'Sort',
      category: 'DataWrite',
      description: 'Sort data by a column',
      params: [
        { key: 'column', label: 'Column (name or letter)', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'order', label: 'Order', param_type: 'Select', required: false, default_value: undefined, placeholder: undefined, options: [{ label: 'Ascending', value: 'asc' }, { label: 'Descending', value: 'desc' }], hint: undefined },
      ],
      output_hint: '{ sheet, rows, data }',
    },
    {
      action_type: 'filter',
      label: 'Filter',
      category: 'DataRead',
      description: 'Filter rows by condition',
      params: [
        { key: 'column', label: 'Column', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'op', label: 'Operator', param_type: 'Select', required: false, default_value: undefined, placeholder: undefined, options: [{ label: 'Contains', value: 'contains' }, { label: 'Equals', value: 'equals' }, { label: '>', value: 'gt' }, { label: '>=', value: 'gte' }, { label: '<', value: 'lt' }, { label: '<=', value: 'lte' }, { label: 'Is Empty', value: 'is_empty' }, { label: 'Not Empty', value: 'not_empty' }], hint: undefined },
        { key: 'value', label: 'Filter Value', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ sheet, rows, data }',
    },
    {
      action_type: 'update',
      label: 'Update Cells',
      category: 'DataWrite',
      description: 'Update specific cells',
      params: [
        { key: 'updates', label: 'Cell updates', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'sheets',
      label: 'List Sheets',
      category: 'DataRead',
      description: 'List all sheets in the workbook',
      params: [
      ],
      output_hint: '{ sheets: [name, ...] }',
    },
  ],
  word: [
    {
      action_type: 'read',
      label: 'Read Document',
      category: 'DataRead',
      description: 'Read the full document content',
      params: [
      ],
      output_hint: '{ paragraphs, full_text }',
    },
    {
      action_type: 'write',
      label: 'Write Content',
      category: 'DataWrite',
      description: 'Write paragraphs to the document',
      params: [
        { key: 'value', label: 'Content (text or paragraphs)', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'create',
      label: 'Create Document',
      category: 'DataWrite',
      description: 'Create a new document with optional title',
      params: [
        { key: 'title', label: 'Document Title', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'replace',
      label: 'Replace Text',
      category: 'DataWrite',
      description: 'Find and replace text in the document',
      params: [
        { key: 'old_text', label: 'Find Text', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'new_text', label: 'Replace With', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'merge',
      label: 'Merge Documents',
      category: 'DataWrite',
      description: 'Merge multiple docx files into one',
      params: [
        { key: 'files', label: 'File paths (array)', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'insert_table',
      label: 'Insert Table',
      category: 'DataWrite',
      description: 'Insert a table into the document',
      params: [
        { key: 'data', label: 'Table data (array of rows)', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
  ],
  file: [
    {
      action_type: 'read',
      label: 'Read File',
      category: 'DataRead',
      description: 'Read file content as text',
      params: [
        { key: 'path', label: 'File Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ path, content, size, lines }',
    },
    {
      action_type: 'write',
      label: 'Write File',
      category: 'DataWrite',
      description: 'Write content to a file',
      params: [
        { key: 'path', label: 'File Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'content', label: 'Content', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ path, size }',
    },
    {
      action_type: 'append',
      label: 'Append to File',
      category: 'DataWrite',
      description: 'Append content to a file',
      params: [
        { key: 'path', label: 'File Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'content', label: 'Content', param_type: 'Textarea', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'copy',
      label: 'Copy File',
      category: 'FileOperation',
      description: 'Copy a file to a new location',
      params: [
        { key: 'from', label: 'Source Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'to', label: 'Destination Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'move',
      label: 'Move / Rename',
      category: 'FileOperation',
      description: 'Move or rename a file',
      params: [
        { key: 'from', label: 'Source Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'to', label: 'Destination Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'delete',
      label: 'Delete',
      category: 'FileOperation',
      description: 'Delete a file or directory',
      params: [
        { key: 'path', label: 'Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
    {
      action_type: 'list',
      label: 'List Directory',
      category: 'DataRead',
      description: 'List files in a directory',
      params: [
        { key: 'path', label: 'Directory Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'pattern', label: 'File Pattern (glob)', param_type: 'Text', required: false, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '[{ name, path, size, is_dir }]',
    },
    {
      action_type: 'exists',
      label: 'Check Exists',
      category: 'DataRead',
      description: 'Check if a file or directory exists',
      params: [
        { key: 'path', label: 'Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '{ exists: bool }',
    },
    {
      action_type: 'glob',
      label: 'Glob Search',
      category: 'DataRead',
      description: 'Find files matching a pattern',
      params: [
        { key: 'path', label: 'Base Directory', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'pattern', label: 'Glob Pattern', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '[{ name, path }]',
    },
    {
      action_type: 'grep',
      label: 'Grep Search',
      category: 'DataRead',
      description: 'Search file contents for text',
      params: [
        { key: 'path', label: 'File or Directory Path', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
        { key: 'pattern', label: 'Search Pattern', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: '[{ file, line, content }]',
    },
  ],
  clipboard: [
    {
      action_type: 'read',
      label: 'Read Clipboard',
      category: 'DataRead',
      description: 'Read text from the clipboard',
      params: [
      ],
      output_hint: '{ text }',
    },
    {
      action_type: 'write',
      label: 'Write Clipboard',
      category: 'Clipboard',
      description: 'Write text to the clipboard',
      params: [
        { key: 'text', label: 'Text', param_type: 'Text', required: true, default_value: undefined, placeholder: undefined, options: undefined, hint: undefined },
      ],
      output_hint: undefined,
    },
  ],
};
