// nodes/mod.rs — 节点系统
pub mod approval;
pub mod array;
pub mod browser;
pub mod browser_container;
pub mod clipboard;
pub mod clipboard_container;
pub mod condition;
pub mod convert;
pub mod cursor;
pub mod data;
pub mod delay;
pub mod error_utils;
pub mod excel;
pub mod excel_container;
pub mod file;
pub mod file_container;
pub mod file_save;
pub mod http;
pub mod json_parse;
pub mod kimi_browser;
pub mod loop_node;
pub mod map;
pub mod mcp_node;
#[cfg(feature = "gui")]
pub mod mouse_keyboard;
pub mod node_registry;
pub mod notify;
pub mod ocr;
pub mod parallel;
#[cfg(feature = "gui")]
pub mod print;
pub mod regex;
pub mod registry;
pub mod script;
pub mod shell;
pub mod sub_workflow;
pub mod text_template;
pub mod traits;
pub mod web_scrape;
pub mod webbridge;
pub mod while_node;
#[cfg(feature = "gui")]
pub mod window;
pub mod word;
pub mod word_container;
