// nodes/mod.rs — 节点系统
pub mod approval;
pub mod browser_container;
pub mod clipboard;
pub mod condition;
pub mod cursor;
pub mod data;
pub mod delay;
pub mod error_utils;
pub mod excel;
pub mod excel_container;
pub mod file;
pub mod file_container;
pub mod http;
pub mod loop_node;
pub mod map;
pub mod mcp_node;
#[cfg(feature = "gui")]
pub mod mouse_keyboard;
pub mod node_registry;
pub mod ocr;
pub mod parallel;
#[cfg(feature = "gui")]
pub mod print;
pub mod regex;
pub mod registry;
pub mod script;
pub mod shell;
pub mod sub_workflow;
pub mod traits;
pub mod web_scrape;
pub mod webbridge;
pub mod while_node;
#[cfg(feature = "gui")]
pub mod window;
pub mod word;
pub mod word_container;
// v8.5 触发器节点
pub mod trigger_cron;
pub mod trigger_webhook;
pub mod trigger_file;
pub mod webhook_response;
// v8.6 实用节点 + AI
pub mod json_transform;
pub mod data_filter;
pub mod llm_chat;
pub mod prompt_template;
pub mod email_send;
pub mod database_query;
// v8.8 IM 集成
pub mod im_message;
